// @generated
// This file is @generated by prost-build.
/// Agent registration request
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterRequest {
    #[prost(string, tag="1")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub node_name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub kubernetes_version: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub agent_version: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub model_version: ::prost::alloc::string::String,
}
/// Agent registration response
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterResponse {
    #[prost(bool, tag="1")]
    pub success: bool,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub config: ::core::option::Option<AgentConfig>,
}
/// Agent configuration from API
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentConfig {
    #[prost(int32, tag="1")]
    pub collection_interval_seconds: i32,
    #[prost(int32, tag="2")]
    pub prediction_interval_seconds: i32,
    #[prost(int32, tag="3")]
    pub sync_interval_seconds: i32,
    #[prost(bool, tag="4")]
    pub anomaly_detection_enabled: bool,
}
/// Batch of metrics from agent
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetricsBatch {
    #[prost(string, tag="1")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub node_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub timestamp: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    #[prost(message, repeated, tag="4")]
    pub metrics: ::prost::alloc::vec::Vec<ContainerMetrics>,
    #[prost(message, repeated, tag="5")]
    pub predictions: ::prost::alloc::vec::Vec<ResourceProfile>,
    #[prost(message, repeated, tag="6")]
    pub anomalies: ::prost::alloc::vec::Vec<Anomaly>,
}
/// Container resource metrics
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContainerMetrics {
    #[prost(string, tag="1")]
    pub container_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub pod_name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub deployment: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub timestamp: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    /// CPU metrics
    #[prost(float, tag="6")]
    pub cpu_usage_cores: f32,
    #[prost(uint64, tag="7")]
    pub cpu_throttled_periods: u64,
    #[prost(uint64, tag="8")]
    pub cpu_throttled_time_ns: u64,
    /// Memory metrics
    #[prost(uint64, tag="9")]
    pub memory_usage_bytes: u64,
    #[prost(uint64, tag="10")]
    pub memory_working_set_bytes: u64,
    #[prost(uint64, tag="11")]
    pub memory_cache_bytes: u64,
    #[prost(uint64, tag="12")]
    pub memory_rss_bytes: u64,
    /// Network metrics
    #[prost(uint64, tag="13")]
    pub network_rx_bytes: u64,
    #[prost(uint64, tag="14")]
    pub network_tx_bytes: u64,
}
/// Resource profile prediction
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResourceProfile {
    #[prost(string, tag="1")]
    pub container_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub pod_name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub deployment: ::prost::alloc::string::String,
    /// Recommended resources
    #[prost(uint32, tag="5")]
    pub cpu_request_millicores: u32,
    #[prost(uint32, tag="6")]
    pub cpu_limit_millicores: u32,
    #[prost(uint64, tag="7")]
    pub memory_request_bytes: u64,
    #[prost(uint64, tag="8")]
    pub memory_limit_bytes: u64,
    /// Prediction metadata
    #[prost(float, tag="9")]
    pub confidence: f32,
    #[prost(string, tag="10")]
    pub model_version: ::prost::alloc::string::String,
    #[prost(message, optional, tag="11")]
    pub generated_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    /// Time window for recommendation
    #[prost(enumeration="TimeWindow", tag="12")]
    pub time_window: i32,
}
/// Anomaly detection result
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Anomaly {
    #[prost(string, tag="1")]
    pub container_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub pod_name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(enumeration="AnomalyType", tag="4")]
    pub r#type: i32,
    #[prost(enumeration="Severity", tag="5")]
    pub severity: i32,
    #[prost(string, tag="6")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag="7")]
    pub detected_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    /// Type-specific details
    #[prost(oneof="anomaly::Details", tags="8, 9, 10")]
    pub details: ::core::option::Option<anomaly::Details>,
}
/// Nested message and enum types in `Anomaly`.
pub mod anomaly {
    /// Type-specific details
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Details {
        #[prost(message, tag="8")]
        MemoryLeak(super::MemoryLeakDetails),
        #[prost(message, tag="9")]
        CpuSpike(super::CpuSpikeDetails),
        #[prost(message, tag="10")]
        OomRisk(super::OomRiskDetails),
    }
}
/// Memory leak anomaly details
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MemoryLeakDetails {
    #[prost(double, tag="1")]
    pub slope_bytes_per_second: f64,
    #[prost(message, optional, tag="2")]
    pub projected_oom_time: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    #[prost(float, tag="3")]
    pub confidence: f32,
}
/// CPU spike anomaly details
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CpuSpikeDetails {
    #[prost(double, tag="1")]
    pub current_usage: f64,
    #[prost(double, tag="2")]
    pub expected_usage: f64,
    #[prost(double, tag="3")]
    pub z_score: f64,
}
/// OOM risk anomaly details
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OomRiskDetails {
    #[prost(int32, tag="1")]
    pub oom_kills_last_hour: i32,
    #[prost(uint64, tag="2")]
    pub recommended_memory_increase_bytes: u64,
}
/// Metrics sync response
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SyncResponse {
    #[prost(bool, tag="1")]
    pub success: bool,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub metrics_received: i64,
    #[prost(int64, tag="4")]
    pub predictions_received: i64,
}
/// Model update request
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModelRequest {
    #[prost(string, tag="1")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub current_model_version: ::prost::alloc::string::String,
}
/// Model update response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelResponse {
    #[prost(bool, tag="1")]
    pub update_available: bool,
    #[prost(string, tag="2")]
    pub new_version: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="3")]
    pub model_weights: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="4")]
    pub checksum: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub metadata: ::core::option::Option<ModelMetadata>,
}
/// Model metadata
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelMetadata {
    #[prost(string, tag="1")]
    pub version: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub created_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    #[prost(float, tag="3")]
    pub validation_accuracy: f32,
    #[prost(int64, tag="4")]
    pub size_bytes: i64,
}
/// Federated learning gradients upload
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GradientsRequest {
    #[prost(string, tag="1")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub model_version: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="3")]
    pub gradients: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag="4")]
    pub sample_count: i64,
}
/// Gradients upload response
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GradientsResponse {
    #[prost(bool, tag="1")]
    pub success: bool,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
}
/// Time window for recommendations
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TimeWindow {
    Unspecified = 0,
    Peak = 1,
    OffPeak = 2,
    Weekly = 3,
}
impl TimeWindow {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TIME_WINDOW_UNSPECIFIED",
            Self::Peak => "TIME_WINDOW_PEAK",
            Self::OffPeak => "TIME_WINDOW_OFF_PEAK",
            Self::Weekly => "TIME_WINDOW_WEEKLY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TIME_WINDOW_UNSPECIFIED" => Some(Self::Unspecified),
            "TIME_WINDOW_PEAK" => Some(Self::Peak),
            "TIME_WINDOW_OFF_PEAK" => Some(Self::OffPeak),
            "TIME_WINDOW_WEEKLY" => Some(Self::Weekly),
            _ => None,
        }
    }
}
/// Anomaly types
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AnomalyType {
    Unspecified = 0,
    MemoryLeak = 1,
    CpuSpike = 2,
    OomRisk = 3,
}
impl AnomalyType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ANOMALY_TYPE_UNSPECIFIED",
            Self::MemoryLeak => "ANOMALY_TYPE_MEMORY_LEAK",
            Self::CpuSpike => "ANOMALY_TYPE_CPU_SPIKE",
            Self::OomRisk => "ANOMALY_TYPE_OOM_RISK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ANOMALY_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "ANOMALY_TYPE_MEMORY_LEAK" => Some(Self::MemoryLeak),
            "ANOMALY_TYPE_CPU_SPIKE" => Some(Self::CpuSpike),
            "ANOMALY_TYPE_OOM_RISK" => Some(Self::OomRisk),
            _ => None,
        }
    }
}
/// Severity levels
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Severity {
    Unspecified = 0,
    Warning = 1,
    Critical = 2,
}
impl Severity {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SEVERITY_UNSPECIFIED",
            Self::Warning => "SEVERITY_WARNING",
            Self::Critical => "SEVERITY_CRITICAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SEVERITY_UNSPECIFIED" => Some(Self::Unspecified),
            "SEVERITY_WARNING" => Some(Self::Warning),
            "SEVERITY_CRITICAL" => Some(Self::Critical),
            _ => None,
        }
    }
}
include!("predictor.v1.tonic.rs");
// @@protoc_insertion_point(module)