// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: predictor/v1/predictor.proto

package predictorv1

import (
	"context"
	"io"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Ensure io is used
var _ = io.EOF

// PredictorSyncClient is the client API for PredictorSync service.
type PredictorSyncClient interface {
	// Register agent with the API
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Stream metrics from agent to API
	SyncMetrics(ctx context.Context, opts ...grpc.CallOption) (PredictorSync_SyncMetricsClient, error)
	// Get model updates
	GetModelUpdate(ctx context.Context, in *ModelRequest, opts ...grpc.CallOption) (*ModelResponse, error)
	// Upload federated learning gradients
	UploadGradients(ctx context.Context, in *GradientsRequest, opts ...grpc.CallOption) (*GradientsResponse, error)
}

type predictorSyncClient struct {
	cc grpc.ClientConnInterface
}

// NewPredictorSyncClient creates a new PredictorSync client
func NewPredictorSyncClient(cc grpc.ClientConnInterface) PredictorSyncClient {
	return &predictorSyncClient{cc}
}

func (c *predictorSyncClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/predictor.v1.PredictorSync/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PredictorSync_SyncMetricsClient is the client stream for SyncMetrics
type PredictorSync_SyncMetricsClient interface {
	Send(*MetricsBatch) error
	CloseAndRecv() (*SyncResponse, error)
	grpc.ClientStream
}

type predictorSyncSyncMetricsClient struct {
	grpc.ClientStream
}

func (x *predictorSyncSyncMetricsClient) Send(m *MetricsBatch) error {
	return x.ClientStream.SendMsg(m)
}

func (x *predictorSyncSyncMetricsClient) CloseAndRecv() (*SyncResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SyncResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *predictorSyncClient) SyncMetrics(ctx context.Context, opts ...grpc.CallOption) (PredictorSync_SyncMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &PredictorSync_ServiceDesc.Streams[0], "/predictor.v1.PredictorSync/SyncMetrics", opts...)
	if err != nil {
		return nil, err
	}
	x := &predictorSyncSyncMetricsClient{stream}
	return x, nil
}

func (c *predictorSyncClient) GetModelUpdate(ctx context.Context, in *ModelRequest, opts ...grpc.CallOption) (*ModelResponse, error) {
	out := new(ModelResponse)
	err := c.cc.Invoke(ctx, "/predictor.v1.PredictorSync/GetModelUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *predictorSyncClient) UploadGradients(ctx context.Context, in *GradientsRequest, opts ...grpc.CallOption) (*GradientsResponse, error) {
	out := new(GradientsResponse)
	err := c.cc.Invoke(ctx, "/predictor.v1.PredictorSync/UploadGradients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PredictorSyncServer is the server API for PredictorSync service.
type PredictorSyncServer interface {
	// Register agent with the API
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Stream metrics from agent to API
	SyncMetrics(PredictorSync_SyncMetricsServer) error
	// Get model updates
	GetModelUpdate(context.Context, *ModelRequest) (*ModelResponse, error)
	// Upload federated learning gradients
	UploadGradients(context.Context, *GradientsRequest) (*GradientsResponse, error)
	mustEmbedUnimplementedPredictorSyncServer()
}

// UnimplementedPredictorSyncServer must be embedded to have forward compatible implementations.
type UnimplementedPredictorSyncServer struct{}

func (UnimplementedPredictorSyncServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func (UnimplementedPredictorSyncServer) SyncMetrics(PredictorSync_SyncMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method SyncMetrics not implemented")
}

func (UnimplementedPredictorSyncServer) GetModelUpdate(context.Context, *ModelRequest) (*ModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelUpdate not implemented")
}

func (UnimplementedPredictorSyncServer) UploadGradients(context.Context, *GradientsRequest) (*GradientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadGradients not implemented")
}

func (UnimplementedPredictorSyncServer) mustEmbedUnimplementedPredictorSyncServer() {}

// UnsafePredictorSyncServer may be embedded to opt out of forward compatibility for this service.
type UnsafePredictorSyncServer interface {
	mustEmbedUnimplementedPredictorSyncServer()
}

// PredictorSync_SyncMetricsServer is the server stream for SyncMetrics
type PredictorSync_SyncMetricsServer interface {
	SendAndClose(*SyncResponse) error
	Recv() (*MetricsBatch, error)
	grpc.ServerStream
}

type predictorSyncSyncMetricsServer struct {
	grpc.ServerStream
}

func (x *predictorSyncSyncMetricsServer) SendAndClose(m *SyncResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *predictorSyncSyncMetricsServer) Recv() (*MetricsBatch, error) {
	m := new(MetricsBatch)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PredictorSync_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictorSyncServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/predictor.v1.PredictorSync/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictorSyncServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PredictorSync_SyncMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PredictorSyncServer).SyncMetrics(&predictorSyncSyncMetricsServer{stream})
}

func _PredictorSync_GetModelUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictorSyncServer).GetModelUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/predictor.v1.PredictorSync/GetModelUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictorSyncServer).GetModelUpdate(ctx, req.(*ModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PredictorSync_UploadGradients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictorSyncServer).UploadGradients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/predictor.v1.PredictorSync/UploadGradients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictorSyncServer).UploadGradients(ctx, req.(*GradientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PredictorSync_ServiceDesc is the grpc.ServiceDesc for PredictorSync service.
var PredictorSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "predictor.v1.PredictorSync",
	HandlerType: (*PredictorSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _PredictorSync_Register_Handler,
		},
		{
			MethodName: "GetModelUpdate",
			Handler:    _PredictorSync_GetModelUpdate_Handler,
		},
		{
			MethodName: "UploadGradients",
			Handler:    _PredictorSync_UploadGradients_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncMetrics",
			Handler:       _PredictorSync_SyncMetrics_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "predictor/v1/predictor.proto",
}

// RegisterPredictorSyncServer registers the server implementation
func RegisterPredictorSyncServer(s grpc.ServiceRegistrar, srv PredictorSyncServer) {
	s.RegisterService(&PredictorSync_ServiceDesc, srv)
}
