// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: predictor/v1/predictor.proto

package predictorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Time window for recommendations
type TimeWindow int32

const (
	TimeWindow_TIME_WINDOW_UNSPECIFIED TimeWindow = 0
	TimeWindow_TIME_WINDOW_PEAK        TimeWindow = 1
	TimeWindow_TIME_WINDOW_OFF_PEAK    TimeWindow = 2
	TimeWindow_TIME_WINDOW_WEEKLY      TimeWindow = 3
)

// Enum value maps for TimeWindow.
var (
	TimeWindow_name = map[int32]string{
		0: "TIME_WINDOW_UNSPECIFIED",
		1: "TIME_WINDOW_PEAK",
		2: "TIME_WINDOW_OFF_PEAK",
		3: "TIME_WINDOW_WEEKLY",
	}
	TimeWindow_value = map[string]int32{
		"TIME_WINDOW_UNSPECIFIED": 0,
		"TIME_WINDOW_PEAK":        1,
		"TIME_WINDOW_OFF_PEAK":    2,
		"TIME_WINDOW_WEEKLY":      3,
	}
)

func (x TimeWindow) Enum() *TimeWindow {
	p := new(TimeWindow)
	*p = x
	return p
}

func (x TimeWindow) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeWindow) Descriptor() protoreflect.EnumDescriptor {
	return file_predictor_v1_predictor_proto_enumTypes[0].Descriptor()
}

func (TimeWindow) Type() protoreflect.EnumType {
	return &file_predictor_v1_predictor_proto_enumTypes[0]
}

func (x TimeWindow) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeWindow.Descriptor instead.
func (TimeWindow) EnumDescriptor() ([]byte, []int) {
	return file_predictor_v1_predictor_proto_rawDescGZIP(), []int{0}
}

// Anomaly types
type AnomalyType int32

const (
	AnomalyType_ANOMALY_TYPE_UNSPECIFIED AnomalyType = 0
	AnomalyType_ANOMALY_TYPE_MEMORY_LEAK AnomalyType = 1
	AnomalyType_ANOMALY_TYPE_CPU_SPIKE   AnomalyType = 2
	AnomalyType_ANOMALY_TYPE_OOM_RISK    AnomalyType = 3
)

// Enum value maps for AnomalyType.
var (
	AnomalyType_name = map[int32]string{
		0: "ANOMALY_TYPE_UNSPECIFIED",
		1: "ANOMALY_TYPE_MEMORY_LEAK",
		2: "ANOMALY_TYPE_CPU_SPIKE",
		3: "ANOMALY_TYPE_OOM_RISK",
	}
	AnomalyType_value = map[string]int32{
		"ANOMALY_TYPE_UNSPECIFIED": 0,
		"ANOMALY_TYPE_MEMORY_LEAK": 1,
		"ANOMALY_TYPE_CPU_SPIKE":   2,
		"ANOMALY_TYPE_OOM_RISK":    3,
	}
)

func (x AnomalyType) Enum() *AnomalyType {
	p := new(AnomalyType)
	*p = x
	return p
}

func (x AnomalyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnomalyType) Descriptor() protoreflect.EnumDescriptor {
	return file_predictor_v1_predictor_proto_enumTypes[1].Descriptor()
}

func (AnomalyType) Type() protoreflect.EnumType {
	return &file_predictor_v1_predictor_proto_enumTypes[1]
}

func (x AnomalyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnomalyType.Descriptor instead.
func (AnomalyType) EnumDescriptor() ([]byte, []int) {
	return file_predictor_v1_predictor_proto_rawDescGZIP(), []int{1}
}

// Severity levels
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_WARNING     Severity = 1
	Severity_SEVERITY_CRITICAL    Severity = 2
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_WARNING",
		2: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_WARNING":     1,
		"SEVERITY_CRITICAL":    2,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_predictor_v1_predictor_proto_enumTypes[2].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_predictor_v1_predictor_proto_enumTypes[2]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_predictor_v1_predictor_proto_rawDescGZIP(), []int{2}
}

// Agent registration request
type RegisterRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentId           string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	NodeName          string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	KubernetesVersion string                 `protobuf:"bytes,3,opt,name=kubernetes_version,json=kubernetesVersion,proto3" json:"kubernetes_version,omitempty"`
	AgentVersion      string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ModelVersion      string                 `protobuf:"bytes,5,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_predictor_v1_predictor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_v1_predictor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_predictor_v1_predictor_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *RegisterRequest) GetKubernetesVersion() string {
	if x != nil {
		return x.KubernetesVersion
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

// Agent registration response
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Config        *AgentConfig           `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_predictor_v1_predictor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_v1_predictor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_predictor_v1_predictor_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetConfig() *AgentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// Agent configuration from API
type AgentConfig struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	CollectionIntervalSeconds int32                  `protobuf:"varint,1,opt,name=collection_interval_seconds,json=collectionIntervalSeconds,proto3" json:"collection_interval_seconds,omitempty"`
	PredictionIntervalSeconds int32                  `protobuf:"varint,2,opt,name=prediction_interval_seconds,json=predictionIntervalSeconds,proto3" json:"prediction_interval_seconds,omitempty"`
	SyncIntervalSeconds       int32                  `protobuf:"varint,3,opt,name=sync_interval_seconds,json=syncIntervalSeconds,proto3" json:"sync_interval_seconds,omitempty"`
	AnomalyDetectionEnabled   bool                   `protobuf:"varint,4,opt,name=anomaly_detection_enabled,json=anomalyDetectionEnabled,proto3" json:"anomaly_detection_enabled,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_predictor_v1_predictor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_v1_predictor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_predictor_v1_predictor_proto_rawDescGZIP(), []int{2}
}

func (x *AgentConfig) GetCollectionIntervalSeconds() int32 {
	if x != nil {
		return x.CollectionIntervalSeconds
	}
	return 0
}

func (x *AgentConfig) GetPredictionIntervalSeconds() int32 {
	if x != nil {
		return x.PredictionIntervalSeconds
	}
	return 0
}

func (x *AgentConfig) GetSyncIntervalSeconds() int32 {
	if x != nil {
		return x.SyncIntervalSeconds
	}
	return 0
}

func (x *AgentConfig) GetAnomalyDetectionEnabled() bool {
	if x != nil {
		return x.AnomalyDetectionEnabled
	}
	return false
}

// Batch of metrics from agent
type MetricsBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       []*ContainerMetrics    `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Predictions   []*ResourceProfile     `protobuf:"bytes,5,rep,name=predictions,proto3" json:"predictions,omitempty"`
	Anomalies     []*Anomaly             `protobuf:"bytes,6,rep,name=anomalies,proto3" json:"anomalies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsBatch) Reset() {
	*x = MetricsBatch{}
	mi := &file_predictor_v1_predictor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsBatch) ProtoMessage() {}

func (x *MetricsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_v1_predictor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsBatch.ProtoReflect.Descriptor instead.
func (*MetricsBatch) Descriptor() ([]byte, []int) {
	return file_predictor_v1_predictor_proto_rawDescGZIP(), []int{3}
}

func (x *MetricsBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricsBatch) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *MetricsBatch) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricsBatch) GetMetrics() []*ContainerMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *MetricsBatch) GetPredictions() []*ResourceProfile {
	if x != nil {
		return x.Predictions
	}
	return nil
}

func (x *MetricsBatch) GetAnomalies() []*Anomaly {
	if x != nil {
		return x.Anomalies
	}
	return nil
}

// Container resource metrics
type ContainerMetrics struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ContainerId string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	PodName     string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Namespace   string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Deployment  string                 `protobuf:"bytes,4,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Timestamp   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// CPU metrics
	CpuUsageCores       float32 `protobuf:"fixed32,6,opt,name=cpu_usage_cores,json=cpuUsageCores,proto3" json:"cpu_usage_cores,omitempty"`
	CpuThrottledPeriods uint64  `protobuf:"varint,7,opt,name=cpu_throttled_periods,json=cpuThrottledPeriods,proto3" json:"cpu_throttled_periods,omitempty"`
	CpuThrottledTimeNs  uint64  `protobuf:"varint,8,opt,name=cpu_throttled_time_ns,json=cpuThrottledTimeNs,proto3" json:"cpu_throttled_time_ns,omitempty"`
	// Memory metrics
	MemoryUsageBytes      uint64 `protobuf:"varint,9,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	MemoryWorkingSetBytes uint64 `protobuf:"varint,10,opt,name=memory_working_set_bytes,json=memoryWorkingSetBytes,proto3" json:"memory_working_set_bytes,omitempty"`
	MemoryCacheBytes      uint64 `protobuf:"varint,11,opt,name=memory_cache_bytes,json=memoryCacheBytes,proto3" json:"memory_cache_bytes,omitempty"`
	MemoryRssBytes        uint64 `protobuf:"varint,12,opt,name=memory_rss_bytes,json=memoryRssBytes,proto3" json:"memory_rss_bytes,omitempty"`
	// Network metrics
	NetworkRxBytes uint64 `protobuf:"varint,13,opt,name=network_rx_bytes,json=networkRxBytes,proto3" json:"network_rx_bytes,omitempty"`
	NetworkTxBytes uint64 `protobuf:"varint,14,opt,name=network_tx_bytes,json=networkTxBytes,proto3" json:"network_tx_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContainerMetrics) Reset() {
	*x = ContainerMetrics{}
	mi := &file_predictor_v1_predictor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMetrics) ProtoMessage() {}

func (x *ContainerMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_v1_predictor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerMetrics.ProtoReflect.Descriptor instead.
func (*ContainerMetrics) Descriptor() ([]byte, []int) {
	return file_predictor_v1_predictor_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerMetrics) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerMetrics) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *ContainerMetrics) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ContainerMetrics) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *ContainerMetrics) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ContainerMetrics) GetCpuUsageCores() float32 {
	if x != nil {
		return x.CpuUsageCores
	}
	return 0
}

func (x *ContainerMetrics) GetCpuThrottledPeriods() uint64 {
	if x != nil {
		return x.CpuThrottledPeriods
	}
	return 0
}

func (x *ContainerMetrics) GetCpuThrottledTimeNs() uint64 {
	if x != nil {
		return x.CpuThrottledTimeNs
	}
	return 0
}

func (x *ContainerMetrics) GetMemoryUsageBytes() uint64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *ContainerMetrics) GetMemoryWorkingSetBytes() uint64 {
	if x != nil {
		return x.MemoryWorkingSetBytes
	}
	return 0
}

func (x *ContainerMetrics) GetMemoryCacheBytes() uint64 {
	if x != nil {
		return x.MemoryCacheBytes
	}
	return 0
}

func (x *ContainerMetrics) GetMemoryRssBytes() uint64 {
	if x != nil {
		return x.MemoryRssBytes
	}
	return 0
}

func (x *ContainerMetrics) GetNetworkRxBytes() uint64 {
	if x != nil {
		return x.NetworkRxBytes
	}
	return 0
}

func (x *ContainerMetrics) GetNetworkTxBytes() uint64 {
	if x != nil {
		return x.NetworkTxBytes
	}
	return 0
}

// Resource profile prediction
type ResourceProfile struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ContainerId string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	PodName     string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Namespace   string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Deployment  string                 `protobuf:"bytes,4,opt,name=deployment,proto3" json:"deployment,omitempty"`
	// Recommended resources
	CpuRequestMillicores uint32 `protobuf:"varint,5,opt,name=cpu_request_millicores,json=cpuRequestMillicores,proto3" json:"cpu_request_millicores,omitempty"`
	CpuLimitMillicores   uint32 `protobuf:"varint,6,opt,name=cpu_limit_millicores,json=cpuLimitMillicores,proto3" json:"cpu_limit_millicores,omitempty"`
	MemoryRequestBytes   uint64 `protobuf:"varint,7,opt,name=memory_request_bytes,json=memoryRequestBytes,proto3" json:"memory_request_bytes,omitempty"`
	MemoryLimitBytes     uint64 `protobuf:"varint,8,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	// Prediction metadata
	Confidence   float32                `protobuf:"fixed32,9,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ModelVersion string                 `protobuf:"bytes,10,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	GeneratedAt  *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	// Time window for recommendation
	TimeWindow    TimeWindow `protobuf:"varint,12,opt,name=time_window,json=timeWindow,proto3,enum=predictor.v1.TimeWindow" json:"time_window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceProfile) Reset() {
	*x = ResourceProfile{}
	mi := &file_predictor_v1_predictor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceProfile) ProtoMessage() {}

func (x *ResourceProfile) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_v1_predictor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceProfile.ProtoReflect.Descriptor instead.
func (*ResourceProfile) Descriptor() ([]byte, []int) {
	return file_predictor_v1_predictor_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceProfile) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ResourceProfile) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *ResourceProfile) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceProfile) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *ResourceProfile) GetCpuRequestMillicores() uint32 {
	if x != nil {
		return x.CpuRequestMillicores
	}
	return 0
}

func (x *ResourceProfile) GetCpuLimitMillicores() uint32 {
	if x != nil {
		return x.CpuLimitMillicores
	}
	return 0
}

func (x *ResourceProfile) GetMemoryRequestBytes() uint64 {
	if x != nil {
		return x.MemoryRequestBytes
	}
	return 0
}

func (x *ResourceProfile) GetMemoryLimitBytes() uint64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *ResourceProfile) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ResourceProfile) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *ResourceProfile) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *ResourceProfile) GetTimeWindow() TimeWindow {
	if x != nil {
		return x.TimeWindow
	}
	return TimeWindow_TIME_WINDOW_UNSPECIFIED
}

// Anomaly detection result
type Anomaly struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ContainerId string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	PodName     string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Namespace   string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type        AnomalyType            `protobuf:"varint,4,opt,name=type,proto3,enum=predictor.v1.AnomalyType" json:"type,omitempty"`
	Severity    Severity               `protobuf:"varint,5,opt,name=severity,proto3,enum=predictor.v1.Severity" json:"severity,omitempty"`
	Message     string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	DetectedAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	// Type-specific details
	//
	// Types that are valid to be assigned to Details:
	//
	//	*Anomaly_MemoryLeak
	//	*Anomaly_CpuSpike
	//	*Anomaly_OomRisk
	Details       isAnomaly_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Anomaly) Reset() {
	*x = Anomaly{}
	mi := &file_predictor_v1_predictor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Anomaly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Anomaly) ProtoMessage() {}

func (x *Anomaly) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_v1_predictor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Anomaly.ProtoReflect.Descriptor instead.
func (*Anomaly) Descriptor() ([]byte, []int) {
	return file_predictor_v1_predictor_proto_rawDescGZIP(), []int{6}
}

func (x *Anomaly) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *Anomaly) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *Anomaly) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Anomaly) GetType() AnomalyType {
	if x != nil {
		return x.Type
	}
	return AnomalyType_ANOMALY_TYPE_UNSPECIFIED
}

func (x *Anomaly) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Anomaly) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Anomaly) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

func (x *Anomaly) GetDetails() isAnomaly_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Anomaly) GetMemoryLeak() *MemoryLeakDetails {
	if x != nil {
		if x, ok := x.Details.(*Anomaly_MemoryLeak); ok {
			return x.MemoryLeak
		}
	}
	return nil
}

func (x *Anomaly) GetCpuSpike() *CpuSpikeDetails {
	if x != nil {
		if x, ok := x.Details.(*Anomaly_CpuSpike); ok {
			return x.CpuSpike
		}
	}
	return nil
}

func (x *Anomaly) GetOomRisk() *OomRiskDetails {
	if x != nil {
		if x, ok := x.Details.(*Anomaly_OomRisk); ok {
			return x.OomRisk
		}
	}
	return nil
}

type isAnomaly_Details interface {
	isAnomaly_Details()
}

type Anomaly_MemoryLeak struct {
	MemoryLeak *MemoryLeakDetails `protobuf:"bytes,8,opt,name=memory_leak,json=memoryLeak,proto3,oneof"`
}

type Anomaly_CpuSpike struct {
	CpuSpike *CpuSpikeDetails `protobuf:"bytes,9,opt,name=cpu_spike,json=cpuSpike,proto3,oneof"`
}

type Anomaly_OomRisk struct {
	OomRisk *OomRiskDetails `protobuf:"bytes,10,opt,name=oom_risk,json=oomRisk,proto3,oneof"`
}

func (*Anomaly_MemoryLeak) isAnomaly_Details() {}

func (*Anomaly_CpuSpike) isAnomaly_Details() {}

func (*Anomaly_OomRisk) isAnomaly_Details() {}

// Memory leak anomaly details
type MemoryLeakDetails struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SlopeBytesPerSecond float64                `protobuf:"fixed64,1,opt,name=slope_bytes_per_second,json=slopeBytesPerSecond,proto3" json:"slope_bytes_per_second,omitempty"`
	ProjectedOomTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=projected_oom_time,json=projectedOomTime,proto3" json:"projected_oom_time,omitempty"`
	Confidence          float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MemoryLeakDetails) Reset() {
	*x = MemoryLeakDetails{}
	mi := &file_predictor_v1_predictor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryLeakDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryLeakDetails) ProtoMessage() {}

func (x *MemoryLeakDetails) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_v1_predictor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryLeakDetails.ProtoReflect.Descriptor instead.
func (*MemoryLeakDetails) Descriptor() ([]byte, []int) {
	return file_predictor_v1_predictor_proto_rawDescGZIP(), []int{7}
}

func (x *MemoryLeakDetails) GetSlopeBytesPerSecond() float64 {
	if x != nil {
		return x.SlopeBytesPerSecond
	}
	return 0
}

func (x *MemoryLeakDetails) GetProjectedOomTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ProjectedOomTime
	}
	return nil
}

func (x *MemoryLeakDetails) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// CPU spike anomaly details
type CpuSpikeDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentUsage  float64                `protobuf:"fixed64,1,opt,name=current_usage,json=currentUsage,proto3" json:"current_usage,omitempty"`
	ExpectedUsage float64                `protobuf:"fixed64,2,opt,name=expected_usage,json=expectedUsage,proto3" json:"expected_usage,omitempty"`
	ZScore        float64                `protobuf:"fixed64,3,opt,name=z_score,json=zScore,proto3" json:"z_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuSpikeDetails) Reset() {
	*x = CpuSpikeDetails{}
	mi := &file_predictor_v1_predictor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuSpikeDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuSpikeDetails) ProtoMessage() {}

func (x *CpuSpikeDetails) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_v1_predictor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuSpikeDetails.ProtoReflect.Descriptor instead.
func (*CpuSpikeDetails) Descriptor() ([]byte, []int) {
	return file_predictor_v1_predictor_proto_rawDescGZIP(), []int{8}
}

func (x *CpuSpikeDetails) GetCurrentUsage() float64 {
	if x != nil {
		return x.CurrentUsage
	}
	return 0
}

func (x *CpuSpikeDetails) GetExpectedUsage() float64 {
	if x != nil {
		return x.ExpectedUsage
	}
	return 0
}

func (x *CpuSpikeDetails) GetZScore() float64 {
	if x != nil {
		return x.ZScore
	}
	return 0
}

// OOM risk anomaly details
type OomRiskDetails struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	OomKillsLastHour               int32                  `protobuf:"varint,1,opt,name=oom_kills_last_hour,json=oomKillsLastHour,proto3" json:"oom_kills_last_hour,omitempty"`
	RecommendedMemoryIncreaseBytes uint64                 `protobuf:"varint,2,opt,name=recommended_memory_increase_bytes,json=recommendedMemoryIncreaseBytes,proto3" json:"recommended_memory_increase_bytes,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *OomRiskDetails) Reset() {
	*x = OomRiskDetails{}
	mi := &file_predictor_v1_predictor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OomRiskDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OomRiskDetails) ProtoMessage() {}

func (x *OomRiskDetails) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_v1_predictor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OomRiskDetails.ProtoReflect.Descriptor instead.
func (*OomRiskDetails) Descriptor() ([]byte, []int) {
	return file_predictor_v1_predictor_proto_rawDescGZIP(), []int{9}
}

func (x *OomRiskDetails) GetOomKillsLastHour() int32 {
	if x != nil {
		return x.OomKillsLastHour
	}
	return 0
}

func (x *OomRiskDetails) GetRecommendedMemoryIncreaseBytes() uint64 {
	if x != nil {
		return x.RecommendedMemoryIncreaseBytes
	}
	return 0
}

// Metrics sync response
type SyncResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message             string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MetricsReceived     int64                  `protobuf:"varint,3,opt,name=metrics_received,json=metricsReceived,proto3" json:"metrics_received,omitempty"`
	PredictionsReceived int64                  `protobuf:"varint,4,opt,name=predictions_received,json=predictionsReceived,proto3" json:"predictions_received,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_predictor_v1_predictor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_v1_predictor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_predictor_v1_predictor_proto_rawDescGZIP(), []int{10}
}

func (x *SyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncResponse) GetMetricsReceived() int64 {
	if x != nil {
		return x.MetricsReceived
	}
	return 0
}

func (x *SyncResponse) GetPredictionsReceived() int64 {
	if x != nil {
		return x.PredictionsReceived
	}
	return 0
}

// Model update request
type ModelRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AgentId             string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CurrentModelVersion string                 `protobuf:"bytes,2,opt,name=current_model_version,json=currentModelVersion,proto3" json:"current_model_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ModelRequest) Reset() {
	*x = ModelRequest{}
	mi := &file_predictor_v1_predictor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelRequest) ProtoMessage() {}

func (x *ModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_v1_predictor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelRequest.ProtoReflect.Descriptor instead.
func (*ModelRequest) Descriptor() ([]byte, []int) {
	return file_predictor_v1_predictor_proto_rawDescGZIP(), []int{11}
}

func (x *ModelRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ModelRequest) GetCurrentModelVersion() string {
	if x != nil {
		return x.CurrentModelVersion
	}
	return ""
}

// Model update response
type ModelResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UpdateAvailable bool                   `protobuf:"varint,1,opt,name=update_available,json=updateAvailable,proto3" json:"update_available,omitempty"`
	NewVersion      string                 `protobuf:"bytes,2,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	ModelWeights    []byte                 `protobuf:"bytes,3,opt,name=model_weights,json=modelWeights,proto3" json:"model_weights,omitempty"`
	Checksum        string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Metadata        *ModelMetadata         `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ModelResponse) Reset() {
	*x = ModelResponse{}
	mi := &file_predictor_v1_predictor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelResponse) ProtoMessage() {}

func (x *ModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_v1_predictor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelResponse.ProtoReflect.Descriptor instead.
func (*ModelResponse) Descriptor() ([]byte, []int) {
	return file_predictor_v1_predictor_proto_rawDescGZIP(), []int{12}
}

func (x *ModelResponse) GetUpdateAvailable() bool {
	if x != nil {
		return x.UpdateAvailable
	}
	return false
}

func (x *ModelResponse) GetNewVersion() string {
	if x != nil {
		return x.NewVersion
	}
	return ""
}

func (x *ModelResponse) GetModelWeights() []byte {
	if x != nil {
		return x.ModelWeights
	}
	return nil
}

func (x *ModelResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *ModelResponse) GetMetadata() *ModelMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Model metadata
type ModelMetadata struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Version            string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ValidationAccuracy float32                `protobuf:"fixed32,3,opt,name=validation_accuracy,json=validationAccuracy,proto3" json:"validation_accuracy,omitempty"`
	SizeBytes          int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ModelMetadata) Reset() {
	*x = ModelMetadata{}
	mi := &file_predictor_v1_predictor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelMetadata) ProtoMessage() {}

func (x *ModelMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_v1_predictor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelMetadata.ProtoReflect.Descriptor instead.
func (*ModelMetadata) Descriptor() ([]byte, []int) {
	return file_predictor_v1_predictor_proto_rawDescGZIP(), []int{13}
}

func (x *ModelMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModelMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ModelMetadata) GetValidationAccuracy() float32 {
	if x != nil {
		return x.ValidationAccuracy
	}
	return 0
}

func (x *ModelMetadata) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

// Federated learning gradients upload
type GradientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	Gradients     []byte                 `protobuf:"bytes,3,opt,name=gradients,proto3" json:"gradients,omitempty"`
	SampleCount   int64                  `protobuf:"varint,4,opt,name=sample_count,json=sampleCount,proto3" json:"sample_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradientsRequest) Reset() {
	*x = GradientsRequest{}
	mi := &file_predictor_v1_predictor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradientsRequest) ProtoMessage() {}

func (x *GradientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_v1_predictor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradientsRequest.ProtoReflect.Descriptor instead.
func (*GradientsRequest) Descriptor() ([]byte, []int) {
	return file_predictor_v1_predictor_proto_rawDescGZIP(), []int{14}
}

func (x *GradientsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GradientsRequest) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *GradientsRequest) GetGradients() []byte {
	if x != nil {
		return x.Gradients
	}
	return nil
}

func (x *GradientsRequest) GetSampleCount() int64 {
	if x != nil {
		return x.SampleCount
	}
	return 0
}

// Gradients upload response
type GradientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradientsResponse) Reset() {
	*x = GradientsResponse{}
	mi := &file_predictor_v1_predictor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradientsResponse) ProtoMessage() {}

func (x *GradientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_predictor_v1_predictor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradientsResponse.ProtoReflect.Descriptor instead.
func (*GradientsResponse) Descriptor() ([]byte, []int) {
	return file_predictor_v1_predictor_proto_rawDescGZIP(), []int{15}
}

func (x *GradientsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GradientsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_predictor_v1_predictor_proto protoreflect.FileDescriptor

const file_predictor_v1_predictor_proto_rawDesc = "" +
	"\n" +
	"\x1cpredictor/v1/predictor.proto\x12\fpredictor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x01\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12-\n" +
	"\x12kubernetes_version\x18\x03 \x01(\tR\x11kubernetesVersion\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12#\n" +
	"\rmodel_version\x18\x05 \x01(\tR\fmodelVersion\"y\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x06config\x18\x03 \x01(\v2\x19.predictor.v1.AgentConfigR\x06config\"\xfd\x01\n" +
	"\vAgentConfig\x12>\n" +
	"\x1bcollection_interval_seconds\x18\x01 \x01(\x05R\x19collectionIntervalSeconds\x12>\n" +
	"\x1bprediction_interval_seconds\x18\x02 \x01(\x05R\x19predictionIntervalSeconds\x122\n" +
	"\x15sync_interval_seconds\x18\x03 \x01(\x05R\x13syncIntervalSeconds\x12:\n" +
	"\x19anomaly_detection_enabled\x18\x04 \x01(\bR\x17anomalyDetectionEnabled\"\xb0\x02\n" +
	"\fMetricsBatch\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x128\n" +
	"\ametrics\x18\x04 \x03(\v2\x1e.predictor.v1.ContainerMetricsR\ametrics\x12?\n" +
	"\vpredictions\x18\x05 \x03(\v2\x1d.predictor.v1.ResourceProfileR\vpredictions\x123\n" +
	"\tanomalies\x18\x06 \x03(\v2\x15.predictor.v1.AnomalyR\tanomalies\"\xea\x04\n" +
	"\x10ContainerMetrics\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"deployment\x18\x04 \x01(\tR\n" +
	"deployment\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12&\n" +
	"\x0fcpu_usage_cores\x18\x06 \x01(\x02R\rcpuUsageCores\x122\n" +
	"\x15cpu_throttled_periods\x18\a \x01(\x04R\x13cpuThrottledPeriods\x121\n" +
	"\x15cpu_throttled_time_ns\x18\b \x01(\x04R\x12cpuThrottledTimeNs\x12,\n" +
	"\x12memory_usage_bytes\x18\t \x01(\x04R\x10memoryUsageBytes\x127\n" +
	"\x18memory_working_set_bytes\x18\n" +
	" \x01(\x04R\x15memoryWorkingSetBytes\x12,\n" +
	"\x12memory_cache_bytes\x18\v \x01(\x04R\x10memoryCacheBytes\x12(\n" +
	"\x10memory_rss_bytes\x18\f \x01(\x04R\x0ememoryRssBytes\x12(\n" +
	"\x10network_rx_bytes\x18\r \x01(\x04R\x0enetworkRxBytes\x12(\n" +
	"\x10network_tx_bytes\x18\x0e \x01(\x04R\x0enetworkTxBytes\"\x94\x04\n" +
	"\x0fResourceProfile\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"deployment\x18\x04 \x01(\tR\n" +
	"deployment\x124\n" +
	"\x16cpu_request_millicores\x18\x05 \x01(\rR\x14cpuRequestMillicores\x120\n" +
	"\x14cpu_limit_millicores\x18\x06 \x01(\rR\x12cpuLimitMillicores\x120\n" +
	"\x14memory_request_bytes\x18\a \x01(\x04R\x12memoryRequestBytes\x12,\n" +
	"\x12memory_limit_bytes\x18\b \x01(\x04R\x10memoryLimitBytes\x12\x1e\n" +
	"\n" +
	"confidence\x18\t \x01(\x02R\n" +
	"confidence\x12#\n" +
	"\rmodel_version\x18\n" +
	" \x01(\tR\fmodelVersion\x12=\n" +
	"\fgenerated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x129\n" +
	"\vtime_window\x18\f \x01(\x0e2\x18.predictor.v1.TimeWindowR\n" +
	"timeWindow\"\xe7\x03\n" +
	"\aAnomaly\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12-\n" +
	"\x04type\x18\x04 \x01(\x0e2\x19.predictor.v1.AnomalyTypeR\x04type\x122\n" +
	"\bseverity\x18\x05 \x01(\x0e2\x16.predictor.v1.SeverityR\bseverity\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12;\n" +
	"\vdetected_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"detectedAt\x12B\n" +
	"\vmemory_leak\x18\b \x01(\v2\x1f.predictor.v1.MemoryLeakDetailsH\x00R\n" +
	"memoryLeak\x12<\n" +
	"\tcpu_spike\x18\t \x01(\v2\x1d.predictor.v1.CpuSpikeDetailsH\x00R\bcpuSpike\x129\n" +
	"\boom_risk\x18\n" +
	" \x01(\v2\x1c.predictor.v1.OomRiskDetailsH\x00R\aoomRiskB\t\n" +
	"\adetails\"\xb2\x01\n" +
	"\x11MemoryLeakDetails\x123\n" +
	"\x16slope_bytes_per_second\x18\x01 \x01(\x01R\x13slopeBytesPerSecond\x12H\n" +
	"\x12projected_oom_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x10projectedOomTime\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\"v\n" +
	"\x0fCpuSpikeDetails\x12#\n" +
	"\rcurrent_usage\x18\x01 \x01(\x01R\fcurrentUsage\x12%\n" +
	"\x0eexpected_usage\x18\x02 \x01(\x01R\rexpectedUsage\x12\x17\n" +
	"\az_score\x18\x03 \x01(\x01R\x06zScore\"\x8a\x01\n" +
	"\x0eOomRiskDetails\x12-\n" +
	"\x13oom_kills_last_hour\x18\x01 \x01(\x05R\x10oomKillsLastHour\x12I\n" +
	"!recommended_memory_increase_bytes\x18\x02 \x01(\x04R\x1erecommendedMemoryIncreaseBytes\"\xa0\x01\n" +
	"\fSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10metrics_received\x18\x03 \x01(\x03R\x0fmetricsReceived\x121\n" +
	"\x14predictions_received\x18\x04 \x01(\x03R\x13predictionsReceived\"]\n" +
	"\fModelRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x122\n" +
	"\x15current_model_version\x18\x02 \x01(\tR\x13currentModelVersion\"\xd5\x01\n" +
	"\rModelResponse\x12)\n" +
	"\x10update_available\x18\x01 \x01(\bR\x0fupdateAvailable\x12\x1f\n" +
	"\vnew_version\x18\x02 \x01(\tR\n" +
	"newVersion\x12#\n" +
	"\rmodel_weights\x18\x03 \x01(\fR\fmodelWeights\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\x127\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1b.predictor.v1.ModelMetadataR\bmetadata\"\xb4\x01\n" +
	"\rModelMetadata\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12/\n" +
	"\x13validation_accuracy\x18\x03 \x01(\x02R\x12validationAccuracy\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\"\x93\x01\n" +
	"\x10GradientsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\x12\x1c\n" +
	"\tgradients\x18\x03 \x01(\fR\tgradients\x12!\n" +
	"\fsample_count\x18\x04 \x01(\x03R\vsampleCount\"G\n" +
	"\x11GradientsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*q\n" +
	"\n" +
	"TimeWindow\x12\x1b\n" +
	"\x17TIME_WINDOW_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TIME_WINDOW_PEAK\x10\x01\x12\x18\n" +
	"\x14TIME_WINDOW_OFF_PEAK\x10\x02\x12\x16\n" +
	"\x12TIME_WINDOW_WEEKLY\x10\x03*\x80\x01\n" +
	"\vAnomalyType\x12\x1c\n" +
	"\x18ANOMALY_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ANOMALY_TYPE_MEMORY_LEAK\x10\x01\x12\x1a\n" +
	"\x16ANOMALY_TYPE_CPU_SPIKE\x10\x02\x12\x19\n" +
	"\x15ANOMALY_TYPE_OOM_RISK\x10\x03*Q\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x01\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x022\xc2\x02\n" +
	"\rPredictorSync\x12I\n" +
	"\bRegister\x12\x1d.predictor.v1.RegisterRequest\x1a\x1e.predictor.v1.RegisterResponse\x12G\n" +
	"\vSyncMetrics\x12\x1a.predictor.v1.MetricsBatch\x1a\x1a.predictor.v1.SyncResponse(\x01\x12I\n" +
	"\x0eGetModelUpdate\x12\x1a.predictor.v1.ModelRequest\x1a\x1b.predictor.v1.ModelResponse\x12R\n" +
	"\x0fUploadGradients\x12\x1e.predictor.v1.GradientsRequest\x1a\x1f.predictor.v1.GradientsResponseB\xd2\x01\n" +
	"\x10com.predictor.v1B\x0ePredictorProtoP\x01Z]github.com/container-resource-predictor/recommendation-api/api/proto/predictor/v1;predictorv1\xa2\x02\x03PXX\xaa\x02\fPredictor.V1\xca\x02\fPredictor\\V1\xe2\x02\x18Predictor\\V1\\GPBMetadata\xea\x02\rPredictor::V1b\x06proto3"

var (
	file_predictor_v1_predictor_proto_rawDescOnce sync.Once
	file_predictor_v1_predictor_proto_rawDescData []byte
)

func file_predictor_v1_predictor_proto_rawDescGZIP() []byte {
	file_predictor_v1_predictor_proto_rawDescOnce.Do(func() {
		file_predictor_v1_predictor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_predictor_v1_predictor_proto_rawDesc), len(file_predictor_v1_predictor_proto_rawDesc)))
	})
	return file_predictor_v1_predictor_proto_rawDescData
}

var file_predictor_v1_predictor_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_predictor_v1_predictor_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_predictor_v1_predictor_proto_goTypes = []any{
	(TimeWindow)(0),               // 0: predictor.v1.TimeWindow
	(AnomalyType)(0),              // 1: predictor.v1.AnomalyType
	(Severity)(0),                 // 2: predictor.v1.Severity
	(*RegisterRequest)(nil),       // 3: predictor.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 4: predictor.v1.RegisterResponse
	(*AgentConfig)(nil),           // 5: predictor.v1.AgentConfig
	(*MetricsBatch)(nil),          // 6: predictor.v1.MetricsBatch
	(*ContainerMetrics)(nil),      // 7: predictor.v1.ContainerMetrics
	(*ResourceProfile)(nil),       // 8: predictor.v1.ResourceProfile
	(*Anomaly)(nil),               // 9: predictor.v1.Anomaly
	(*MemoryLeakDetails)(nil),     // 10: predictor.v1.MemoryLeakDetails
	(*CpuSpikeDetails)(nil),       // 11: predictor.v1.CpuSpikeDetails
	(*OomRiskDetails)(nil),        // 12: predictor.v1.OomRiskDetails
	(*SyncResponse)(nil),          // 13: predictor.v1.SyncResponse
	(*ModelRequest)(nil),          // 14: predictor.v1.ModelRequest
	(*ModelResponse)(nil),         // 15: predictor.v1.ModelResponse
	(*ModelMetadata)(nil),         // 16: predictor.v1.ModelMetadata
	(*GradientsRequest)(nil),      // 17: predictor.v1.GradientsRequest
	(*GradientsResponse)(nil),     // 18: predictor.v1.GradientsResponse
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_predictor_v1_predictor_proto_depIdxs = []int32{
	5,  // 0: predictor.v1.RegisterResponse.config:type_name -> predictor.v1.AgentConfig
	19, // 1: predictor.v1.MetricsBatch.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 2: predictor.v1.MetricsBatch.metrics:type_name -> predictor.v1.ContainerMetrics
	8,  // 3: predictor.v1.MetricsBatch.predictions:type_name -> predictor.v1.ResourceProfile
	9,  // 4: predictor.v1.MetricsBatch.anomalies:type_name -> predictor.v1.Anomaly
	19, // 5: predictor.v1.ContainerMetrics.timestamp:type_name -> google.protobuf.Timestamp
	19, // 6: predictor.v1.ResourceProfile.generated_at:type_name -> google.protobuf.Timestamp
	0,  // 7: predictor.v1.ResourceProfile.time_window:type_name -> predictor.v1.TimeWindow
	1,  // 8: predictor.v1.Anomaly.type:type_name -> predictor.v1.AnomalyType
	2,  // 9: predictor.v1.Anomaly.severity:type_name -> predictor.v1.Severity
	19, // 10: predictor.v1.Anomaly.detected_at:type_name -> google.protobuf.Timestamp
	10, // 11: predictor.v1.Anomaly.memory_leak:type_name -> predictor.v1.MemoryLeakDetails
	11, // 12: predictor.v1.Anomaly.cpu_spike:type_name -> predictor.v1.CpuSpikeDetails
	12, // 13: predictor.v1.Anomaly.oom_risk:type_name -> predictor.v1.OomRiskDetails
	19, // 14: predictor.v1.MemoryLeakDetails.projected_oom_time:type_name -> google.protobuf.Timestamp
	16, // 15: predictor.v1.ModelResponse.metadata:type_name -> predictor.v1.ModelMetadata
	19, // 16: predictor.v1.ModelMetadata.created_at:type_name -> google.protobuf.Timestamp
	3,  // 17: predictor.v1.PredictorSync.Register:input_type -> predictor.v1.RegisterRequest
	6,  // 18: predictor.v1.PredictorSync.SyncMetrics:input_type -> predictor.v1.MetricsBatch
	14, // 19: predictor.v1.PredictorSync.GetModelUpdate:input_type -> predictor.v1.ModelRequest
	17, // 20: predictor.v1.PredictorSync.UploadGradients:input_type -> predictor.v1.GradientsRequest
	4,  // 21: predictor.v1.PredictorSync.Register:output_type -> predictor.v1.RegisterResponse
	13, // 22: predictor.v1.PredictorSync.SyncMetrics:output_type -> predictor.v1.SyncResponse
	15, // 23: predictor.v1.PredictorSync.GetModelUpdate:output_type -> predictor.v1.ModelResponse
	18, // 24: predictor.v1.PredictorSync.UploadGradients:output_type -> predictor.v1.GradientsResponse
	21, // [21:25] is the sub-list for method output_type
	17, // [17:21] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_predictor_v1_predictor_proto_init() }
func file_predictor_v1_predictor_proto_init() {
	if File_predictor_v1_predictor_proto != nil {
		return
	}
	file_predictor_v1_predictor_proto_msgTypes[6].OneofWrappers = []any{
		(*Anomaly_MemoryLeak)(nil),
		(*Anomaly_CpuSpike)(nil),
		(*Anomaly_OomRisk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_predictor_v1_predictor_proto_rawDesc), len(file_predictor_v1_predictor_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_predictor_v1_predictor_proto_goTypes,
		DependencyIndexes: file_predictor_v1_predictor_proto_depIdxs,
		EnumInfos:         file_predictor_v1_predictor_proto_enumTypes,
		MessageInfos:      file_predictor_v1_predictor_proto_msgTypes,
	}.Build()
	File_predictor_v1_predictor_proto = out.File
	file_predictor_v1_predictor_proto_goTypes = nil
	file_predictor_v1_predictor_proto_depIdxs = nil
}
